# Generated by Django 4.2.25 on 2025-11-15 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('email', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=10)),
                ('password', models.CharField(default='123456', max_length=20)),
                ('uid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('license', models.CharField(max_length=5)),
                ('depotID', models.CharField(max_length=5)),
            ],
        ),
    ]
