# Generated by Django 4.2.25 on 2025-11-25 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('lineNo', models.BigAutoField(primary_key=True, serialize=False)),
                ('lineName', models.CharField(max_length=20)),
                ('lineFrom', models.CharField(max_length=20)),
                ('lineTo', models.CharField(max_length=20)),
                ('depotID', models.CharField(max_length=5)),
                ('vtype', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=10)),
                ('depotID', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vid', models.BigAutoField(primary_key=True, serialize=False)),
                ('lp', models.CharField(max_length=10)),
                ('vtype', models.CharField(max_length=10)),
                ('req', models.CharField(max_length=5)),
                ('depotID', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('uid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='admin_profile', serialize=False, to='myapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('uid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='driver_profile', serialize=False, to='myapp.user')),
                ('license', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('sid', models.BigAutoField(primary_key=True, serialize=False)),
                ('dtime', models.DateTimeField()),
                ('atime', models.DateTimeField()),
                ('dlocation', models.CharField(max_length=20)),
                ('lineNo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='myapp.line')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='myapp.user')),
                ('vid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='myapp.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tbegin', models.DateTimeField()),
                ('tend', models.DateTimeField()),
                ('reason', models.CharField(max_length=100)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='myapp.user')),
            ],
        ),
    ]
