# Generated by Django 4.2.25 on 2025-11-25 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromDepot', models.CharField(max_length=5)),
                ('toDepot', models.CharField(max_length=5)),
                ('data', models.DateField()),
                ('note', models.CharField(max_length=500)),
                ('vid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='myapp.vehicle')),
            ],
        ),
    ]
