# Generated by Django 4.2.25 on 2025-11-24 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('email', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=10)),
                ('password', models.CharField(default='admin123', max_length=20)),
                ('uid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('depotID', models.CharField(max_length=5)),
            ],
        ),
    ]
