# Generated by Django 4.2.25 on 2025-11-24 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='uid',
            field=models.BigIntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
