# Generated by Django 4.2.25 on 2025-11-25 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_transfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='note',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
