# Generated by Django 4.2.25 on 2025-11-25 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_transfer_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transfer',
            old_name='data',
            new_name='date',
        ),
    ]
