# Generated by Django 4.2.25 on 2025-12-16 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_data_transfer_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='run_duration',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
