# Generated by Django 4.2.25 on 2025-12-16 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_line_run_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='req',
        ),
    ]
