# Generated by Django 4.2.25 on 2025-12-16 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_vehicle_req'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='vtype',
            field=models.CharField(max_length=10),
        ),
    ]
