# Generated by Django 4.2.25 on 2025-12-19 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_line_vtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='id',
        ),
        migrations.AddField(
            model_name='leave',
            name='approved',
            field=models.CharField(default=0, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leave',
            name='lid',
            field=models.BigAutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
